### PR TITLE
Migrated \docs\get-started\index.rst to markdown

### PR DESCRIPTION
**Pull request by UdokaVrede**
Hi @danielabutano I migrated this file to markdown, I would also go ahead to migrate all other files.
I also made changes, modified links, better formatting using markdown

### CODE REVIEW

**Comment by hyounes4560** [comment]
Hey, @UdokaVrede is this related to the dev doc project? Thanks

**Comment by UdokaVrede** [comment]
Hi hyounes, thanks for the review, this is related to the dev doc project found here https://github.com/intermine/im-docs/blob/master/docs/get-started/tutorial/index.rst

**Comment by hyounes4560** [comment]
> Hi hyounes, thanks for the review, this is related to the dev doc project found here https://github.com/intermine/im-docs/blob/master/docs/get-started/tutorial/index.rst

This repo is for the user docs project.

**Comment by danielabutano** [comment]
Dear @UdokaVrede thanks for the PR. In the proposal please hightlight if you have applied some changes e.g. typos, better formatting, links added. THANKS!

**Comment by UdokaVrede** [comment]
> Dear @UdokaVrede thanks for the PR. In the proposal please hightlight if you have applied some changes e.g. typos, better formatting, links added. THANKS!

Alright

**Comment by danielabutano** [comment]
This is related to im-docs, not training portal.

**Pull request closed without merging**
