### PR TITLE
Intermine-Logo added to the header 

### PR DESCRIPTION
**Pull request by Anisha-28**

### CODE REVIEW

**Comment by danielabutano** [comment]
Hi @Anisha-28, thanks for the PR. Please rename the logo into something like intermine-logo?
THANKS!

**Review by danielabutano — COMMENTED** [review]
Hi @Anisha-28, thanks for the PR. Please rename the logo into something like intermine-logo?
THANKS!

**Comment by Anisha-28** [comment]
Hey @danielabutano as advised changes have been done.

**Comment by danielabutano** [comment]
Hi @Anisha-28 I close the PR because I do no see your changes as commits in this PR

**Pull request closed without merging**
