### PR TITLE
Lizzy

### PR DESCRIPTION
**Pull request by LizzyKate**
I created a short tutorial on the "Template Search Documentation"

### CODE REVIEW

**Comment by rachellyne** [comment]
Hi,

A nice try.  Could you take a look at the original documentation - https://flymine.readthedocs.io/en/latest/.  It will give you some ideas on how you may be able to improve the wording.  For instance, the filter on the templates page allows you to filter by data type, not description.  E.g., you could write the term "expression" to filter to all templates involved in expression (similar to the expression tab above).  Rather than saving the data "pops out", say something like the "to filter the list according to the search term". 

Can you improve the screenshots?  The circling of key areas should be neater - e.g use a coloured rectangle.  You could also add some annotated screenshots.

Hope this helps.

**Comment by LizzyKate** [comment]
Yes it helps a lot. Thank you... will fix it immediately.

**Comment by LizzyKate** [comment]
> Hi,
> 
> A nice try. Could you take a look at the original documentation - https://flymine.readthedocs.io/en/latest/. It will give you some ideas on how you may be able to improve the wording. For instance, the filter on the templates page allows you to filter by data type, not description. E.g., you could write the term "expression" to filter to all templates involved in expression (similar to the expression tab above). Rather than saving the data "pops out", say something like the "to filter the list according to the search term".
> 
> Can you improve the screenshots? The circling of key areas should be neater - e.g use a coloured rectangle. You could also add some annotated screenshots.
> 
> Hope this helps.

I have improved the wordings and images. Please can you review. Thanks

**Comment by LizzyKate** [comment]
> Hi,
> 
> A nice try. Could you take a look at the original documentation - https://flymine.readthedocs.io/en/latest/. It will give you some ideas on how you may be able to improve the wording. For instance, the filter on the templates page allows you to filter by data type, not description. E.g., you could write the term "expression" to filter to all templates involved in expression (similar to the expression tab above). Rather than saving the data "pops out", say something like the "to filter the list according to the search term".
> 
> Can you improve the screenshots? The circling of key areas should be neater - e.g use a coloured rectangle. You could also add some annotated screenshots.
> 
> Hope this helps.

Please rachel, can you review my latest commits

**Comment by LizzyKate** [comment]
> Hi,
> 
> A nice try. Could you take a look at the original documentation - https://flymine.readthedocs.io/en/latest/. It will give you some ideas on how you may be able to improve the wording. For instance, the filter on the templates page allows you to filter by data type, not description. E.g., you could write the term "expression" to filter to all templates involved in expression (similar to the expression tab above). Rather than saving the data "pops out", say something like the "to filter the list according to the search term".
> 
> Can you improve the screenshots? The circling of key areas should be neater - e.g use a coloured rectangle. You could also add some annotated screenshots.
> 
> Hope this helps.

Hello Rachel, I did some updates. Please review

**Comment by heralden** [comment]
Thank you for participating in the Outreachy contribution phase.

I'm closing this PR as the project has finished and the documentation has been completed in https://github.com/intermine/intermine-user-docs/

**Pull request closed without merging**
