### PR TITLE
Adding Sample documentation for Bluemine UI

### PR DESCRIPTION
**Pull request by Ruth-ikegah**
Hi @rachellyne 

I have written out sample documentation for using the template search in the BlueMine UI.
While I work on other features, please can you review and suggest any corrections that I should implement.
Thanks :)

### CODE REVIEW

**Comment by rachellyne** [comment]
Hi Ruth.  This looks nice.  I cannot view the images from the text - do you know how to make the links work?  A couple of points:  for the "search for any term", (we call this the keyword search),  the text says "Click on the gene to be taken to the report page", but  the screenshot shows an Exon (it is better to show a link to a Gene).  Can you expand the template search section - for example, show some other options such as how to run a template with a list of genes?

**Comment by Ruth-ikegah** [comment]
> Hi Ruth. This looks nice. I cannot view the images from the text - do you know how to make the links work? A couple of points: for the "search for any term", (we call this the keyword search), the text says "Click on the gene to be taken to the report page", but the screenshot shows an Exon (it is better to show a link to a Gene). Can you expand the template search section - for example, show some other options such as how to run a template with a list of genes?

Hi Rachellyne, thanks for this review. Yes for the images I will try using another option. I will also make the suggested changes right now. Thanks.

**Comment by Ruth-ikegah** [comment]
Hi, @rachellyne thanks for the last review. I have made some changes as requested earlier. Please help me review it. Thanks.

**Comment by Ruth-ikegah** [comment]
Hi @rachellyne, please a gentle reminder on reviewing the updated changes. Thanks

**Comment by rachellyne** [comment]
Hi Ruth,

Sorry, for the delay!  The section on how to create a list from the search is nice.  I would add a screenshot to show a report page too - most people who use the faceted (keyword) search will probably visit report pages as the next step.  Also, your top hit still seems to show an Exon - it should be a gene.  When I search Tumour Necrosis factor, the top hit is a Gene (symbol TNF).  Do you get the same?

**Comment by Ruth-ikegah** [comment]
Hi @rachellyne, thanks again for the review. I am sorry I did not change that earlier about the top list chat. I just did now.

**Comment by rachellyne** [comment]
It looks really nice now.

**Comment by heralden** [comment]
Thank you for participating in the Outreachy contribution phase.

I'm closing this PR as the project has finished and the documentation has been completed in https://github.com/intermine/intermine-user-docs/

**Comment by Ruth-ikegah** [comment]
That's awesome @uosl ! Thanks

**Pull request closed without merging**
