### PR TITLE
Faceted search

### PR DESCRIPTION
**Pull request by hyounes4560**
I created 3 pages, Home (index.md) page, Exercise 1: Faceted Search page, and Exercise 1: Answers. Screenshots and short videos for my localhost are attached. I used relative links to link the pages I created as shown in the video. I also updated the text according to the new user interface (Bluegenes).

**Home page**

Screenshot (530) 

<br/>

**Excercise 1: Faceted Search page**

Screenshot (532)

<br/>

**Excercise 1: Answers page**

Screenshot (533)

**Live Demonstration**
 _Part 1_

ezgif com-gif-maker

_Part 2_

ezgif com-gif-maker (1)

### CODE REVIEW

**Comment by rachellyne** [comment]
This is very nice.  Could you add a bit more?  It might be better to pick something further down in the user manual, e.g lists or templates (rather than the tutorial section) so we can see some more wording and some annotated screenshots?  It would be really great if you could send us a video of one section too (please email to the mentors).

**Comment by hyounes4560** [comment]
> This is very nice. Could you add a bit more? It might be better to pick something further down in the user manual, e.g lists or templates (rather than the tutorial section) so we can see some more wording and some annotated screenshots? It would be really great if you could send us a video of one section too (please email to the mentors).

Thanks for your feedback,

I will work on another section today, so hopefully it will be ready soon. What software should I use for the video? Thanks again

**Comment by rachellyne** [comment]
We can recommend Open Broadcaster Software (https://obsproject.com/). It is free, should be sufficient for this task, and has multiple video tutorials you can find online.  If you are already familiar with other software though, please use it.

**Comment by hyounes4560** [comment]
> We can recommend Open Broadcaster Software (https://obsproject.com/). It is free, should be sufficient for this task, and has multiple video tutorials you can find online. If you are already familiar with other software though, please use it.

I worked with other software but I will check your suggestions. Thanks again for your feedback and prompt reply.

**Comment by hyounes4560** [comment]
@rachellyne I just pushed a new section for templets search. Please ignore the order of the pages on the left side as I just focused on the actual writing and images. 
ezgif com-gif-maker (2)

**Comment by Ruth-ikegah** [comment]
Hi, @hyounes4560 Nice PR. I am a fellow outreachy applicant. Please I have a question. What tool did you use to edit your screenshots?

**Comment by rachellyne** [comment]
That looks very nice - very clear annotations on the screenshots and the text is good.  I look forward to seeing your video.

**Comment by hyounes4560** [comment]
> Hi, @hyounes4560 Nice PR. I am a fellow outreachy applicant. Please I have a question. What tool did you use to edit your screenshots?

Hi Ruth, thanks. I just used the Paint software on a Windows machine; nothing fancy. Good luck

**Comment by Ruth-ikegah** [comment]
Hi @hyounes4560 Please I have a question, I see you were able to build on local which is very nice. Please can you tell me how you were able to do it? I inspected your PR but I am quite confused. Here is [my PR](https://github.com/intermine/training-portal/pull/16) 
I'm sorry for the inconveniences

**Comment by heralden** [comment]
Thank you for participating in the Outreachy contribution phase.

I'm closing this PR as the project has finished and the documentation has been completed in https://github.com/intermine/intermine-user-docs/

**Pull request closed without merging**
