### PR TITLE
Region Search Documentation

### PR DESCRIPTION
**Pull request by keneficent**
Hi @rachellyne I wrote a sample documentation for using the region search on the BlueMine interface. Please review and suggest any corrections I should make. Cheers!

### CODE REVIEW

**Comment by rachellyne** [comment]
Hi, could you add some screenshots from the BlueGenes interface?

**Comment by keneficent** [comment]
Hi @rachellyne thank you for the review. I have added screenshots from the BlueGenes Interface as advised.

**Comment by rachellyne** [comment]
Hi,  I can't view the screenshots - are you able to embed the screenshots into the document?

**Comment by keneficent** [comment]
> Hi, I can't view the screenshots - are you able to embed the screenshots into the document?



> Hi, I can't view the screenshots - are you able to embed the screenshots into the document?

HI, I embedded the screenshots in the second commit labeled "Update Region Search Documentation"

**Comment by heralden** [comment]
Thank you for participating in the Outreachy contribution phase.

I'm closing this PR as the project has finished and the documentation has been completed in https://github.com/intermine/intermine-user-docs/

**Pull request closed without merging**
