### PR TITLE
add template search session

### PR DESCRIPTION
**Pull request by Ifyokoh**

### CODE REVIEW

**Review by danielabutano — COMMENTED** [review]
The new user documentation has to based on the new user interface ([Bluegenes](http://bluegenes.apps.intermine.org/)).
The current template-search page contains more info. This PR covers only the first 2 sections.

**Comment by Ifyokoh** [comment]
Thank you @danielabutano  for the review. I only did the first 2 sections to show you and know if I'm on the right direction. If yes, I will continue to completing the full template search page.

**Comment by danielabutano** [comment]
Please replace the screenshots and be aware that the new interface might be sligtly different. THANKS!!!

**Comment by Ifyokoh** [comment]
Apologies for asking a lot of questions,  by replacing the screenshots, do you mean they are not clear enough?

**Comment by Ifyokoh** [comment]
Hi @danielabutano I've updated the page and replaced the screenshots

**Comment by danielabutano** [comment]
screenshots still refer to the old interface. We want screenshots from the new interface here!! http://bluegenes.apps.intermine.org/
THANKS!

**Comment by rachellyne** [comment]
Hi,
Can you tidy up the red boxes on the screenshots?  Do you know how to make nice rectangular boxes?  Also, it might be easier for someone to follow if there is some annotation on the actual screenshot - e.g where you have referred to 3 and 4 on the screenshot, it may not be clear where in the text this is.  Could you try adding some annotation boxes?  

The wording for the edit template section isn't quite clear - i.e how do you navigate from a template to the query builder.

Hope this helps,

**Comment by Ifyokoh** [comment]
Hi @rachellyne thanks for the feedback. I will work on the annotation boxes and let you know if I encounter any challenge

**Comment by Ifyokoh** [comment]
Hi @rachellyne I've added the annotated screenshots. Please take a look

**Comment by heralden** [comment]
Thank you for participating in the Outreachy contribution phase.

I'm closing this PR as the project has finished and the documentation has been completed in https://github.com/intermine/intermine-user-docs/

**Pull request closed without merging**
