### PR TITLE
Sampledocs

### PR DESCRIPTION
**Pull request by iambami**
Hi @rachellyne I just wrote a sample documentation on keyword search for Intermine interface. Can you please review this and give  me feedback on the correctios to make?

### CODE REVIEW

**Comment by rachellyne** [comment]
@iambami this is a good start but we really need to see more than this. Can you add some screenshots, preferably with annotations?  Also, watch your spelling - there are a couple of typos - e.g. quotation -> quotation

**Comment by iambami** [comment]
> @iambami this is a good start but we really need to see more than this. Can you add some screenshots, preferably with annotations? Also, watch your spelling - there are a couple of typos - e.g. quotation -> quotation

Thanks, @rachellyne for the review. I will make the necessary corrections. Regarding that part you said "see more than this" do you mean I should add more content to this or I should create more samples?

**Comment by rachellyne** [comment]
Both really, but most importantly I would like to see some annotated screenshots.  Thanks.

**Comment by iambami** [comment]
Alright, thanks for the review. I'll make all the changes.

**Comment by iambami** [comment]
Hi Rachel, I added more images to it. I'd like you to review it.
 Thank you.

**Comment by rachellyne** [comment]
Great - nice start.  I can't view the screenshots inline with the text - only from the images directory - are you able to link to them from the text doc?  The screenshots are nicely annotated.  Why do they appear on a squared background?  Are you able to change that?  I would include a larger screenshot of the results as well, so the user can get an idea of the page layout and where everything is.

**Comment by iambami** [comment]
Thanks, @rachellyne for the review. 
I will make all corrections.

**Comment by heralden** [comment]
Thank you for participating in the Outreachy contribution phase.

I'm closing this PR as the project has finished and the documentation has been completed in https://github.com/intermine/intermine-user-docs/

**Pull request closed without merging**
